"""initial schema

Revision ID: 16180792f748
Revises:
Create Date: 2026-10-04 21:54:33.137727
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Supabase публикует схему public через REST API по anon-ключу.
# RLS без политик закрывает этот доступ; бот ходит ролью postgres и RLS обходит.
RLS_TABLES = ("users", "habits", "habit_logs", "alembic_version")


revision: str = "16180792f748"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("summary_time", sa.Time(), nullable=True),
        sa.Column(
            "reminders_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("last_summary_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
    )
    op.create_table(
        "habits",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=True),
        sa.Column("schedule_days", sa.SmallInteger(), server_default="127", nullable=False),
        sa.Column("remind_time", sa.Time(), nullable=True),
        sa.Column("last_reminded_on", sa.Date(), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "schedule_days BETWEEN 1 AND 127", name=op.f("ck_habits_schedule_days_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_habits_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habits")),
    )
    op.create_index(
        "ix_habits_user_id_is_archived", "habits", ["user_id", "is_archived"], unique=False
    )
    op.create_table(
        "habit_logs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("habit_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('done', 'skipped')", name=op.f("ck_habit_logs_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
            name=op.f("fk_habit_logs_habit_id_habits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habit_logs")),
        sa.UniqueConstraint("habit_id", "date", name="uq_habit_logs_habit_id_date"),
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        for table in RLS_TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habit_logs")
    op.drop_index("ix_habits_user_id_is_archived", table_name="habits")
    op.drop_table("habits")
    op.drop_table("users")
    # ### end Alembic commands ###
